// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxx_VGiTtAXZQtrCdZE2UjnpQbxBcq_-o',
    appId: '1:702816088574:web:742c931dd81d527f1210af',
    messagingSenderId: '702816088574',
    projectId: 'tiktok-hayat-practice',
    authDomain: 'tiktok-hayat-practice.firebaseapp.com',
    storageBucket: 'tiktok-hayat-practice.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2_BK_zRx4K2sLXefmnxRUfyQQahQNsYY',
    appId: '1:702816088574:android:79c5150a813846e81210af',
    messagingSenderId: '702816088574',
    projectId: 'tiktok-hayat-practice',
    storageBucket: 'tiktok-hayat-practice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjQwpBNe6j7rHsKpbI5tbIhMNSuEFUpEI',
    appId: '1:702816088574:ios:45aa10c53ad4d3101210af',
    messagingSenderId: '702816088574',
    projectId: 'tiktok-hayat-practice',
    storageBucket: 'tiktok-hayat-practice.appspot.com',
    iosClientId: '702816088574-vq7jih13p8il5oebaeb6fn4cp7fuorn9.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
